// student-manager-taro/src/pages/welfare/detail.tsx
import { useEffect, useState } from 'react'
import Taro, { useRouter } from '@tarojs/taro'
import { Button, Image, Text, View } from '@tarojs/components'
import HtmlContent from '@/components/HtmlContent'
import { commonRequest } from '@/utils/request'
import { getGlobalData, refreshAuthFromStorage } from '@/utils/app'
import shareIcon from '@/static/images/card/share.png'
import './detail.scss'

export default function WelfareDetail() {
  const router = useRouter()
  const [detail, setDetail] = useState<any>({})
  const [status, setStatus] = useState<any>()
  const type = `${router.params.type || '1'}`
  const cardId = `${router.params.cardId || ''}`

  const loadStatus = async (id: string) => {
    const { token, userId } = refreshAuthFromStorage()
    if (!userId) return
    const data = await commonRequest<any>('GET', `app/card/info/${id}/${userId}/${type}`, { token }, {}, true).catch(() => undefined)
    setStatus(data || undefined)
  }

  useEffect(() => {
    async function load() {
      if (!cardId) return
      const data = await commonRequest<any>('GET', `app/${type === '1' ? 'vip' : 'welfare'}/info/${cardId}`, {})
      setDetail(data || {})
      loadStatus(cardId)
    }
    load()
  }, [cardId, type])

  const receive = async () => {
    if (!status?.id) return
    await commonRequest('GET', `app/card/update/receive/${status.id}/${type}`, {})
    loadStatus(detail.id || cardId)
  }

  const useCard = async () => {
    if (!status?.id) return
    await commonRequest('GET', `app/card/update/use/${status.id}`, {})
    loadStatus(detail.id || cardId)
  }

  const goToLogin = () => {
    const globalData = getGlobalData()
    globalData.card = { cardId: detail.id || cardId, type }
    Taro.navigateTo({ url: '/pages/index/index?tab=mine' })
  }

  const start = detail.startTime ? detail.startTime.split(' ')[0] : ''
  const end = detail.endTime ? detail.endTime.split(' ')[0] : ''

  return (
    <View className="welfare-detail">
      <View className="card-detail-box">
        <View className="detail-cover" style={{ backgroundImage: detail.avaterUrl ? `url(${detail.avaterUrl})` : undefined }} />
        <Text className="detail-title">{detail.title}</Text>
        <HtmlContent content={detail.remark} />
        {start || end ? <Text className="valid-time">有效期：{start} ~ {end}</Text> : null}
        {detail.rule ? (
          <View className="rule-box">
            <Text className="section-title">使用规则</Text>
            <HtmlContent content={detail.rule} />
          </View>
        ) : null}
      </View>
      <View className="fixed-card-footer">
        <Image className="share-image" src={shareIcon} />
        {status ? (
          <>
            {status.status === '2' ? <Button className="primary-btn action-btn" onClick={receive}>领取</Button> : null}
            {type === '1' && status.status === '1' ? <Button className="primary-btn action-btn done">已领取</Button> : null}
            {type === '2' && status.status === '1' && status.useStatus === '1' ? <Button className="primary-btn action-btn" onClick={useCard}>使用</Button> : null}
            {type === '2' && status.status === '1' && status.useStatus === '2' ? <Button className="primary-btn action-btn done">已使用</Button> : null}
          </>
        ) : (
          <Button className="primary-btn action-btn" onClick={goToLogin}>领取</Button>
        )}
      </View>
    </View>
  )
}

// student-manager-moblie/src/pages/cardpackage/detail.vue
<template>
  <scroll-view class="scroll-view" scroll-y="true">
    <view class="welfare-detail">
      <view class="curtain"></view>
      <view class="card-detail-box">
        <view class="image" :style="{'background-image':'url('+ cardDetail.avaterUrl +')'}"></view>
        <view class="title">{{cardDetail.title}}</view>
        <view class="remark">
          <mp-html :content="cardDetail.remark"/>
        </view>
        <view class="time-rang">
          有效期：{{cardDetail.startTime.split(" ")[0]}} ~ {{cardDetail.endTime.split(" ")[0]}}
        </view>
        <view class="divider"></view>
        <view class="footer-content">
          <mp-html :content="cardDetail.rule"/>
        </view>
      </view>
      <view class="card-footer">
        <view class="card-share"></view>
        <view class="card-click-container" v-if="cardType == '1'">
          <view v-if="userId">
            <view class="card-btn" v-if="cardStatus.status == '2'" @click="cardReceive"><text>领取</text></view>
            <view class="card-btn done" v-if="cardStatus.status == '1'"><text>已领取</text></view>
          </view>
          <view v-if="!userId">
            <view class="card-btn" @click="goToLogin"><text>领取</text></view>
          </view>
        </view>
        <view class="card-click-container" v-if="cardType == '2'">
          <view v-if="userId">
            <view class="card-btn done" v-if="cardStatus.status == '2'" @click="cardReceive"><text>领取</text></view>
            <view v-if="cardStatus.status == '1'">
              <view class="card-btn" v-if="cardStatus.status == '1' && cardStatus.useStatus == '1'" @click="useCard"><text>使用</text></view>
              <view class="card-btn done" v-if="cardStatus.status == '1' && cardStatus.useStatus == '2'"><text>已使用</text></view>
            </view>
          </view>
          <view v-if="!userId">
            <view class="card-btn" @click="goToLogin"><text>领取</text></view>
          </view>
        </view>
      </view>
      <view class="safe-distance-bottom"></view>
    </view>
  </scroll-view>
</template>
<script setup lang="ts">
import {onLoad} from "@dcloudio/uni-app";
import {commonRequest} from "@/utils/request";
import {ref} from "vue";

let { token:accessToken, userId } = getApp().globalData as any
const cardDetail = ref()

const cardStatus = ref()

// const userId = ref()

const cardType = ref<any>()

const cardReceive = async () => {
  let res = await commonRequest('GET',`app/card/update/receive/${cardStatus.value.id}/${cardType.value}`, {}) as any
  if (res){
    uni.showModal({
      title: '领取成功',
      //将值设置为 success 或者直接不用写icon这个参数
      icon: 'success',
      //显示持续时间为 2秒
      duration: 2000,
      showCancel:false,
      success: (res) => {
        console.log(res)
        if (res.confirm) {
          getCardStatus(cardDetail.value.id)
        }
      }
    })
  }
}

const useCard = async () => {
  let res = await commonRequest('GET',`app/card/update/use/${cardStatus.value.id}`, {}) as any
  if (res){
    uni.showModal({
      title: '使用成功',
      //将值设置为 success 或者直接不用写icon这个参数
      icon: 'success',
      //显示持续时间为 2秒
      duration: 2000,
      showCancel:false,
      success: (res) => {
        console.log(res)
        if (res.confirm) {
          getCardStatus(cardDetail.value.id)
        }
      }
    })
  }
}

const getCardStatus = async (cardId:number) => {
  cardStatus.value = await commonRequest('GET',`app/card/info/${cardId}/${userId}/${cardType.value}`, {token:accessToken}) as any
  if (!cardStatus.value){
    uni.showToast({
      title: '温馨提示',
      content: '无法领取，请联系小秘！',
      showCancel: false
    })
  }
}

const goToLogin = () => {
  uni.showModal({
    title: '温馨提示',
    content: '请登录',
    showCancel: false,
    success: (res) => {
      if (res.confirm) {
        // getApp().tologin = '1'
        // getApp().cardId = this.data.cardId
        // getApp().type = '1'
        // getApp().cId = this.data.id
        uni.switchTab({
          url:'pages/mine/index'
        })
      }
    }
  })
}

onLoad(async (options:any) => {
  let { cardId,type } = options
  cardType.value = type
  cardDetail.value = await commonRequest('GET',`app/${type == '1' ? 'vip' : 'welfare'}/info/${cardId}`, {token:accessToken}) as any
  getCardStatus(cardId)

})
</script>

<style lang="scss">
@import "/src/static/css/base";
@import "/src/pages/welfare/cardDetail";
</style>
