// student-manager-taro/src/pages/notice/index.tsx
import { useEffect, useRef, useState } from 'react'
import Taro, { useReachBottom } from '@tarojs/taro'
import { View } from '@tarojs/components'
import GraphicItem from '@/components/GraphicItem'
import { commonRequest } from '@/utils/request'
import { normalizePageResult } from '@/utils/pagination'

export default function Notice() {
  const [list, setList] = useState<any[]>([])
  const [pageNum, setPageNum] = useState(1)
  const [hasMore, setHasMore] = useState(true)
  const loading = useRef(false)
  const pageSize = 10

  const load = async (nextPage = 1, append = false) => {
    if (loading.current) return
    loading.current = true
    try {
      const data = await commonRequest<any>('GET', 'app/notice/list', {}, { pageNum: nextPage, pageSize })
      const page = normalizePageResult<any>(data, nextPage, pageSize)
      setList((prev) => append ? prev.concat(page.list) : page.list)
      setPageNum(nextPage)
      setHasMore(page.hasMore)
    } finally {
      loading.current = false
    }
  }

  useEffect(() => {
    load()
  }, [])

  useReachBottom(() => {
    if (hasMore) load(pageNum + 1, true)
  })

  return (
    <View className="common-box-2">
      {list.length ? list.map((item) => (
        <GraphicItem
          key={item.id}
          title={item.noticeTitle}
          image={item.noticeUrl}
          meta={item.createTime}
          onClick={() => Taro.navigateTo({ url: `/pages/notice/detail?id=${item.id}` })}
        />
      )) : <View className="empty">暂无公告</View>}
    </View>
  )
}

// student-manager-server/src/pages/notice/index.vue
<template>
  <view class="notice content">
    <view class="tab-content common-box-2">
      <custom-graphics-context class="graphics-item" clickName="noticeItem" v-for="item in noticeList" :title="item.noticeTitle" :image="item.noticeUrl" :graphicsContextItem="item" :type="item.type"/>
    </view>
    <view class="footer"></view>
  </view>
</template>

<script setup lang="ts">

import CustomGraphicsContext from "@/components/custom-graphics-context.vue";
import { ref } from "vue";
import {commonRequest} from "@/utils/request";
import {onLoad} from "@dcloudio/uni-app";
import bus from '@/utils/bus'

const noticeList = ref()
const getNoticeList = async () => {
  noticeList.value = await commonRequest('GET','app/notice/list',{}) as any;
}

//跳转到文章详情
bus.on("noticeItem",({id, type}) => {
  uni.navigateTo({
    url:`/pages/notice/detail?id=${id}`
  })
})

onLoad(() => {
  getNoticeList()
})
</script>


<style lang="scss">
@import "/src/static/css/base";
</style>
