// student-manager-server/src/App.vue
<script lang="ts">
export default {
    globalData:{
        token:uni.getStorageSync("token"),
        userId:uni.getStorageSync("userId"),
        toLogin:true,
        card:{
          cardId:'',
          type:''
        }
    },
    onLaunch:(() => {
        console.log("App Launch");
    }),
    onShow:(() => {
    // uni.hideTabBar();
    console.log("App Show");
    }),
    onHide:(() => {
        console.log("App Hide");
    })
}
</script>
<style></style>

// student-manager-taro/src/app.tsx
import { PropsWithChildren } from 'react'
import Taro, { useLaunch } from '@tarojs/taro'
import './app.scss'

export type GlobalData = {
  token: string
  userId: string
  toLogin: boolean
  card: {
    cardId: string
    type: string
  }
}

function App({ children }: PropsWithChildren) {
  useLaunch(() => {
    const app = Taro.getApp()
    app.globalData = {
      token: Taro.getStorageSync('token') || '',
      userId: Taro.getStorageSync('userId') || '',
      toLogin: true,
      card: {
        cardId: '',
        type: ''
      }
    } satisfies GlobalData
  })

  return children
}

export default App
