// student-manager-server/src/pages/profile/index.vue
<template>
  <view class="profile">
    <view class="curtain"></view>
    <view class="common-box">
      <view class="common-title">个人档案</view>
      <view class="profile-content">
        <image class="profile-image" :src="user.archives"></image>
      </view>
    </view>
    <view class="footer"></view>
  </view>
</template>
<script setup lang="ts">
import logo from "@/static/images/associationIntro/logo.png"
import {onLoad} from "@dcloudio/uni-app";
import {commonRequest} from "@/utils/request";
import {ref} from "vue";

let { token:accessToken, userId } = getApp().globalData as any
const user = ref()
onLoad(async (options:any) => {
  user.value = await commonRequest('GET',`app/wxuser/get/${userId}`,{token:accessToken}) as any;
})
</script>
<style lang="scss">
@import "/src/static/css/base";
.profile .common-title{
  font-size: batchXpTarlationRPX(18);
  text-align: justify;
  font-weight: bold;
}

.profile-content{
  padding-top: batchXpTarlationRPX(20);
}
</style>

// student-manager-taro/src/pages/profile/index.tsx
import { useEffect, useState } from 'react'
import { Image, Text, View } from '@tarojs/components'
import { commonRequest } from '@/utils/request'
import { refreshAuthFromStorage } from '@/utils/app'
import avatarDefault from '@/static/images/mine/avatar.png'
import './index.scss'

export default function Profile() {
  const [user, setUser] = useState<any>({})

  useEffect(() => {
    async function load() {
      const { token, userId } = refreshAuthFromStorage()
      if (!userId) return
      const data = await commonRequest<any>('GET', `app/wxuser/get/${userId}`, { token })
      setUser(data || {})
    }
    load()
  }, [])

  const rows = [
    ['姓名', user.name || user.nickName],
    ['电话', user.phone],
    ['单位', user.company],
    ['职务', user.postName],
    ['部门', user.deptName]
  ]

  return (
    <View className="profile common-box">
      <Image className="profile-avatar" src={user.avatarUrl || user.avatar || avatarDefault} />
      {rows.map(([label, value]) => (
        <View className="profile-row" key={label}>
          <Text className="profile-label">{label}</Text>
          <Text className="profile-value">{value || '-'}</Text>
        </View>
      ))}
    </View>
  )
}
