// student-manager-taro/src/pages/activity/detail.tsx
import { useEffect, useState } from 'react'
import Taro, { useRouter } from '@tarojs/taro'
import { Button, Image, Text, View } from '@tarojs/components'
import HtmlContent from '@/components/HtmlContent'
import { commonRequest } from '@/utils/request'
import { refreshAuthFromStorage } from '@/utils/app'
import activityIcon from '@/static/images/activity/activity-icon.png'
import locationIcon from '@/static/images/activity/location.png'
import './index.scss'

export default function ActivityDetail() {
  const router = useRouter()
  const id = `${router.params.id || ''}`
  const [detail, setDetail] = useState<any>({})

  const load = async () => {
    const { userId } = refreshAuthFromStorage()
    const data = await commonRequest<any>('GET', `app/activity/get/${id}/${userId || ''}`)
    setDetail(data || {})
  }

  useEffect(() => {
    if (id) load()
  }, [id])

  const sign = async () => {
    const { token, userId } = refreshAuthFromStorage()
    if (!userId) {
      Taro.navigateTo({ url: '/pages/index/index?tab=mine' })
      return
    }
    await commonRequest('GET', `app/sign/add/${userId}/${id}`, { token })
    load()
  }

  const cancelSign = async () => {
    const { token, userId } = refreshAuthFromStorage()
    await commonRequest('DELETE', `app/sign/delete/${userId}/${id}`, { token })
    load()
  }

  return (
    <View className="activity-detail">
      <View className="activity-item">
        <View className="activity-image" style={{ backgroundImage: detail.avaterUrl ? `url(${detail.avaterUrl})` : undefined }}>
          <Text className="activity-time">{(detail.status === '5' ? detail.endTime : detail.startTime)?.split(' ')[0]?.substr(5)}</Text>
        </View>
        <View className="activity-container">
          <View className="activity-info">
            <View className="activity-base">
              <View className="activity-title">
                <Image className="icon" src={activityIcon} />
                <Text>{detail.title}</Text>
              </View>
              <Text className="activity-font">{detail.startTime?.split(' ')[0]} ~ {detail.endTime?.split(' ')[0]}</Text>
              <View className="activity-font row">
                {detail.address ? <Image className="local" src={locationIcon} /> : null}
                <Text>{detail.address || '暂定'}</Text>
              </View>
              <Text className="activity-font">联系人：{detail.contactName || '暂定'}</Text>
              <Text className="activity-font">名额：{detail.signQuota || '-'}</Text>
              <Text className="activity-font">参与对象：{detail.signType === '1' ? '协会会员' : '所有人'}</Text>
            </View>
            {detail.statusName === '报名中'
              ? <Button className="btn" onClick={sign}>报名</Button>
              : <Button className="btn activity-finish" onClick={cancelSign}>取消报名</Button>}
          </View>
        </View>
      </View>
      <View className="activity-sign common-box-2">
        <Text className="section-title">报名情况 ({detail.successNumber || 0}/{detail.signQuota || 0})</Text>
        <View className="sign-users">
          {(detail.signListVOS || []).map((item: any) => (
            <Image key={item.id || item.userId} className="sign-avatar" src={item.avatarUrl || item.avatar} />
          ))}
        </View>
      </View>
      <View className="activity-introduce common-box-2">
        <Text className="section-title">活动详情</Text>
        <HtmlContent content={detail.remark} />
      </View>
    </View>
  )
}

// student-manager-moblie/src/pages/activity/detail.vue
<template>
  <view class="activity-detail">
    <view class="curtain"></view>
    <view class="activity-content">
      <view class="activity-item">
        <view class="activity-image" :style="{'background-image':'url('+ activityDetail.avaterUrl +')'}">
          <view class="activity-time" v-if="activityDetail.status == '5'">
            {{activityDetail.endTime.split(' ')[0].substr(5)}}
          </view>
          <view class="activity-time" v-if="activityDetail.status != '5'">
            {{activityDetail.startTime.split(' ')[0].substr(5)}}
          </view>
        </view>
        <view class="activity-container">
          <view class="activity-info">
            <view class="activity-base">
              <view class="activity-title margin-bottom-10">
                <image class="icon" src="../../static/images/activity/activity-icon.png"></image>
                <text class="text">{{activityDetail.title}}</text>
              </view>
              <view class="activity-date activity-font margin-bottom-5">
                <text>时间：</text>
                <text>{{activityDetail.startTime.split(' ')[0]}} ~ {{activityDetail.endTime.split(' ')[0]}}</text>
              </view>
              <view class="activity-local activity-font margin-bottom-5">
                <text>地点：</text>
                <image class="local" v-if="activityDetail.address" src="../../static/images/activity/location.png"></image>
                <text>{{activityDetail.address ? activityDetail.address : '暂定'}}</text>
              </view>
              <view class="activity-contacts activity-font margin-bottom-5">
                <text>联系人：</text>
                <text>{{activityDetail.contactName ? activityDetail.contactName : '暂定'}}</text>
              </view>
              <view class="activity-quota activity-font margin-bottom-5">
                <text>活动名额：</text>
                <text>{{activityDetail.signQuota}}</text>
              </view>
              <view class="activity-participants activity-font margin-bottom-5">
                <text>参加人员：</text>
                <text>{{activityDetail.signType == '1' ? '协会会员' : '所有人'}}</text>
              </view>
            </view>
            <view class="activity-btn">
              <button class="btn" v-if="activityDetail.statusName != '报名中'" @click="cancelSign(activityDetail.id)">取消报名</button>
              <button class="btn" v-if="activityDetail.statusName == '报名中'" @click="sign(activityDetail.id)">报名</button>
            </view>
          </view>
        </view>
        <view class="activity-sign">
          <view class="activity-sign-text">
            已报名
            <view>({{activityDetail.successNumber}}/{{activityDetail.signQuota}})</view>
          </view>
          <view class="activity-sign-users">
            <view class="users-list">
              <view class="user-item" v-for="item in activityDetail.signListVOS">
                <view class="user-image" :style="{'background-image':'url('+ item.avaterUrl +')'}" v-if="item.avaterUrl"></view>
                <view class="user-image" :style="{'background-image':'url(../../static/images/mine/avatar.png)'}" v-if="!item.avaterUrl"></view>
                <view class="user-name">{{item.userName || item.nickName}}</view>
              </view>
            </view>
          </view>
        </view>
      </view>
    </view>
    <view class="activity-introduce">
      <view class="activity-suspension">活动详情</view>
      <view class="activity-content-title">
        {{activityDetail.title}}
      </view>
      <view class="activity-introduce-content">
        <mp-html :content="activityDetail.remark"/>
      </view>
    </view>
    <view class="footer"></view>
  </view>
</template>
<script setup lang="ts">
import {onLoad} from "@dcloudio/uni-app";
import {commonRequest} from "@/utils/request";
import mpHtml from "@/components/mp-html/mp-html.vue"
import {ref} from "vue";

const activityDetail = ref()

let { token:accessToken, userId } = getApp().globalData as any

const sign = async (id:Number) => {
  let res = await commonRequest('GET',`app/sign/add/${userId}/${id}`,{token:accessToken}) as any;
  if (res){
    uni.showToast({
      title: '恭喜您，报名成功',
      //将值设置为 success 或者直接不用写icon这个参数
      icon: 'success',
      //显示持续时间为 2秒
      duration: 2000
    })
  }
}
const cancelSign = async (id:Number) => {
  let res = await commonRequest('DELETE',`app/sign/delete/${userId}/${id}`,{token:accessToken}) as any;
  if (res){
    uni.showToast({
      title: '取消报名成功',
      //将值设置为 success 或者直接不用写icon这个参数
      icon: 'success',
      //显示持续时间为 2秒
      duration: 2000
    })
  }
}

onLoad(async (options:any) => {
  let { id } = options

  activityDetail.value = await commonRequest('GET',`app/activity/get/${id}/${userId}`) as any;

})
</script>
<style lang="scss">
@import "/src/static/css/base";
@import "activity";
</style>
